# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    environment:
      BUNDLE_PATH: vendor/bundle
      FL_OUTPUT_DIR: output
    macos:
      xcode: "10.2.0"
    steps:
      - restore_cache:
          keys:
          - v1-gems-{{ checksum "Gemfile.lock" }}
          - v1-gems-
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - checkout
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - run:
          name: Build and run tests
          command: bundle exec fastlane ios testlib        
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
