# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: 
          name: Install swiftLint
          command: brew install swiftlint
      - run:
          name: update CocoaPods
          command: sudo gem install cocoapods --pre
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Build and run tests
          command: fastlane ios testlib        
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
